// ─── Warehouse Zone Configuration ─────────────────────────────────────────────
export const ZONE_CONFIG = {
  'Zone A': {
    color: '#3b82f6',
    barClass: 'bg-blue-500',
    textClass: 'text-blue-700',
    lightClass: 'bg-blue-50 border-blue-200',
    dotClass: 'bg-blue-500',
    label: 'Receiving & Prep',
    currentLoadPct: 72,
    maxDailyHours: 18,
  },
  'Zone B': {
    color: '#10b981',
    barClass: 'bg-emerald-500',
    textClass: 'text-emerald-700',
    lightClass: 'bg-emerald-50 border-emerald-200',
    dotClass: 'bg-emerald-500',
    label: 'General Storage',
    currentLoadPct: 58,
    maxDailyHours: 24,
  },
  'Zone C': {
    color: '#8b5cf6',
    barClass: 'bg-violet-500',
    textClass: 'text-violet-700',
    lightClass: 'bg-violet-50 border-violet-200',
    dotClass: 'bg-violet-500',
    label: 'Pick & Pack',
    currentLoadPct: 45,
    maxDailyHours: 20,
  },
  'Zone D': {
    color: '#f97316',
    barClass: 'bg-orange-500',
    textClass: 'text-orange-700',
    lightClass: 'bg-orange-50 border-orange-200',
    dotClass: 'bg-orange-500',
    label: 'Cold Storage',
    currentLoadPct: 89,   // Already near capacity — key to the plot twist
    maxDailyHours: 10,
  },
  'Crossdock': {
    color: '#eab308',
    barClass: 'bg-yellow-500',
    textClass: 'text-yellow-700',
    lightClass: 'bg-yellow-50 border-yellow-200',
    dotClass: 'bg-yellow-500',
    label: 'Crossdock Bay',
    currentLoadPct: 62,
    maxDailyHours: 12,
  },
}

// ─── Site Stats ────────────────────────────────────────────────────────────────
export const SITE_STATS = {
  todayThroughput: 1847,
  dockUtilization: 68,
  activeTeams: 14,
  pendingContainers: 312,
  slaRiskCount: 2,
  avgCycleTimeHours: 4.2,
}

// ─── Yard totals ───────────────────────────────────────────────────────────────
export const TOTAL_CONTAINERS_IN_YARD = 312  // Only top-10 shown by AI priority

// ─── Container Data ────────────────────────────────────────────────────────────
export const CONTAINERS = [
  {
    id: 'CONT-4201',
    poNumber: 'PO-6124',
    category: 'Food & Beverage',
    subcategory: 'Packaged Dry Goods',
    supplier: 'Nestlé',
    ageInYard: 7,
    palletCount: 6,
    estimatedUnits: 840,
    truckId: 'TRK-887',
    dockAssigned: 'Dock 3',
    priority: 'urgent',
    // Pre-scan estimate (based on PO data + historical similar orders)
    initialEstimate: {
      certainty: 62,
      totalHours: 18.5,
      breakdown: { unloading: 3.2, binning: 11.8, crossdocking: 3.5 },
      byZone: {
        'Zone A': { hours: 4.5, units: 210 },
        'Zone B': { hours: 6.3, units: 400 },
        'Zone C': { hours: 1.9, units: 120 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 5.8, units: 110 },
      },
    },
    // Post-scan estimate (revealed after cold-chain items discovered)
    updatedEstimate: {
      certainty: 91,
      totalHours: 31.2,
      breakdown: { unloading: 4.8, binning: 19.4, crossdocking: 7.0 },
      byZone: {
        'Zone A': { hours: 4.5, units: 210 },
        'Zone B': { hours: 5.1, units: 290 },
        'Zone C': { hours: 1.9, units: 120 },
        'Zone D': { hours: 14.3, units: 310 },   // cold chain explosion
        'Crossdock': { hours: 5.4, units: 110 },
      },
    },
    criteria: {
      workloadBalance:      { score: 0.65, label: 'Moderate' },
      ageScore:             { score: 0.95, label: 'Critical' },
      processingEfficiency: { score: 0.88, label: 'High' },
      overall: 0.82,
    },
    updatedCriteria: {
      workloadBalance:      { score: 0.31, label: 'Poor' },
      ageScore:             { score: 0.95, label: 'Critical' },
      processingEfficiency: { score: 0.44, label: 'Low' },
      overall: 0.57,
    },
    isRecommended: true,
    isUpdatedRecommended: false,
    recommendationReasons: [
      'Oldest container at 7 days — approaching SLA breach threshold',
      'Standard F&B processing is highly efficient at this site',
      'Current dock window availability aligns with 18.5 h estimated workload',
    ],
  },
  {
    id: 'CONT-2847',
    poNumber: 'PO-4821',
    category: 'Consumer Electronics',
    subcategory: 'Devices & Accessories',
    supplier: 'Samsung',
    ageInYard: 5,
    palletCount: 10,
    estimatedUnits: 1240,
    truckId: 'TRK-902',
    dockAssigned: 'Dock 7',
    priority: 'high',
    initialEstimate: {
      certainty: 58,
      totalHours: 42.0,
      breakdown: { unloading: 6.5, binning: 28.5, crossdocking: 7.0 },
      byZone: {
        'Zone A': { hours: 8.2, units: 380 },
        'Zone B': { hours: 14.6, units: 520 },
        'Zone C': { hours: 12.2, units: 240 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 7.0, units: 100 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.72, label: 'Good' },
      ageScore:             { score: 0.78, label: 'High' },
      processingEfficiency: { score: 0.68, label: 'Moderate' },
      overall: 0.73,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  {
    id: 'CONT-1943',
    poNumber: 'PO-3876',
    category: 'Home & Garden',
    subcategory: 'Home Décor & Furnishings',
    supplier: 'IKEA',
    ageInYard: 3,
    palletCount: 15,
    estimatedUnits: 2100,
    truckId: 'TRK-761',
    dockAssigned: 'Dock 2',
    priority: 'normal',
    initialEstimate: {
      certainty: 71,
      totalHours: 35.0,
      breakdown: { unloading: 5.0, binning: 24.0, crossdocking: 6.0 },
      byZone: {
        'Zone A': { hours: 6.8, units: 480 },
        'Zone B': { hours: 16.2, units: 920 },
        'Zone C': { hours: 6.0, units: 520 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 6.0, units: 180 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.91, label: 'Excellent' },
      ageScore:             { score: 0.55, label: 'Moderate' },
      processingEfficiency: { score: 0.85, label: 'High' },
      overall: 0.77,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: true,   // becomes recommended after scan reveals cold-chain issue
    recommendationReasons: [],
    updatedRecommendationReasons: [
      'Best workload balance score (91%) — distributes evenly across all available zones',
      'Zero cold-chain requirements — avoids overloading Zone D (currently 89% capacity)',
      'High processing efficiency for Home & Garden category',
      'Estimated 35 h fits current team capacity without overtime risk',
    ],
  },
  {
    id: 'CONT-2599',
    poNumber: 'PO-4502',
    category: 'Sports & Outdoor',
    subcategory: 'Equipment & Apparel',
    supplier: 'Nike',
    ageInYard: 2,
    palletCount: 10,
    estimatedUnits: 1580,
    truckId: 'TRK-443',
    dockAssigned: 'Dock 5',
    priority: 'normal',
    initialEstimate: {
      certainty: 65,
      totalHours: 32.0,
      breakdown: { unloading: 4.8, binning: 21.2, crossdocking: 6.0 },
      byZone: {
        'Zone A': { hours: 5.5, units: 350 },
        'Zone B': { hours: 14.5, units: 720 },
        'Zone C': { hours: 8.0, units: 380 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 4.0, units: 130 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.78, label: 'Good' },
      ageScore:             { score: 0.35, label: 'Low' },
      processingEfficiency: { score: 0.71, label: 'Good' },
      overall: 0.61,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  {
    id: 'CONT-3156',
    poNumber: 'PO-5033',
    category: 'Apparel & Accessories',
    subcategory: 'Mixed Clothing',
    supplier: 'Zara',
    ageInYard: 1,
    palletCount: 8,
    estimatedUnits: 3200,
    truckId: 'TRK-519',
    dockAssigned: 'Dock 1',
    priority: 'low',
    initialEstimate: {
      certainty: 75,
      totalHours: 28.0,
      breakdown: { unloading: 3.5, binning: 22.0, crossdocking: 2.5 },
      byZone: {
        'Zone A': { hours: 5.0, units: 640 },
        'Zone B': { hours: 12.0, units: 1200 },
        'Zone C': { hours: 8.5, units: 1160 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 2.5, units: 200 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.88, label: 'Excellent' },
      ageScore:             { score: 0.15, label: 'Low' },
      processingEfficiency: { score: 0.65, label: 'Moderate' },
      overall: 0.56,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  // ── Containers ranked 6-10 (complete the visible top-10 from 312 in yard) ────
  {
    id: 'CONT-5102',
    poNumber: 'PO-7234',
    category: 'Apparel & Accessories',
    subcategory: 'Athletic Wear',
    supplier: 'Adidas',
    ageInYard: 4,
    palletCount: 8,
    estimatedUnits: 2800,
    truckId: 'TRK-621',
    dockAssigned: 'Dock 8',
    priority: 'high',
    initialEstimate: {
      certainty: 69,
      totalHours: 24.0,
      breakdown: { unloading: 3.2, binning: 18.0, crossdocking: 2.8 },
      byZone: {
        'Zone A': { hours: 4.2, units: 560 },
        'Zone B': { hours: 10.5, units: 1100 },
        'Zone C': { hours: 7.0, units: 960 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 2.3, units: 180 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.74, label: 'Good' },
      ageScore:             { score: 0.65, label: 'Moderate' },
      processingEfficiency: { score: 0.58, label: 'Moderate' },
      overall: 0.54,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  {
    id: 'CONT-6344',
    poNumber: 'PO-8192',
    category: 'Home & Garden',
    subcategory: 'Furniture & Flat-pack',
    supplier: 'West Elm',
    ageInYard: 6,
    palletCount: 18,
    estimatedUnits: 1640,
    truckId: 'TRK-774',
    dockAssigned: 'Dock 4',
    priority: 'urgent',
    initialEstimate: {
      certainty: 55,
      totalHours: 48.0,
      breakdown: { unloading: 7.5, binning: 32.5, crossdocking: 8.0 },
      byZone: {
        'Zone A': { hours: 9.2, units: 320 },
        'Zone B': { hours: 22.0, units: 880 },
        'Zone C': { hours: 8.8, units: 340 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 8.0, units: 100 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.60, label: 'Moderate' },
      ageScore:             { score: 0.88, label: 'High' },
      processingEfficiency: { score: 0.42, label: 'Moderate' },
      overall: 0.51,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  {
    id: 'CONT-7891',
    poNumber: 'PO-9021',
    category: 'Consumer Electronics',
    subcategory: 'Wearables & Peripherals',
    supplier: 'LG Electronics',
    ageInYard: 2,
    palletCount: 7,
    estimatedUnits: 3100,
    truckId: 'TRK-308',
    dockAssigned: 'Dock 9',
    priority: 'normal',
    initialEstimate: {
      certainty: 61,
      totalHours: 30.0,
      breakdown: { unloading: 4.5, binning: 20.5, crossdocking: 5.0 },
      byZone: {
        'Zone A': { hours: 5.8, units: 620 },
        'Zone B': { hours: 10.2, units: 1100 },
        'Zone C': { hours: 9.0, units: 1100 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 5.0, units: 280 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.68, label: 'Good' },
      ageScore:             { score: 0.35, label: 'Low' },
      processingEfficiency: { score: 0.55, label: 'Moderate' },
      overall: 0.48,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  {
    id: 'CONT-4501',
    poNumber: 'PO-3344',
    category: 'Sports & Outdoor',
    subcategory: 'Footwear & Apparel',
    supplier: 'Decathlon',
    ageInYard: 3,
    palletCount: 9,
    estimatedUnits: 4200,
    truckId: 'TRK-091',
    dockAssigned: 'Dock 11',
    priority: 'normal',
    initialEstimate: {
      certainty: 72,
      totalHours: 36.0,
      breakdown: { unloading: 5.0, binning: 26.0, crossdocking: 5.0 },
      byZone: {
        'Zone A': { hours: 6.5, units: 840 },
        'Zone B': { hours: 16.0, units: 1900 },
        'Zone C': { hours: 9.5, units: 1200 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 4.0, units: 260 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.55, label: 'Moderate' },
      ageScore:             { score: 0.55, label: 'Moderate' },
      processingEfficiency: { score: 0.62, label: 'Moderate' },
      overall: 0.45,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
  {
    id: 'CONT-8823',
    poNumber: 'PO-2211',
    category: 'Food & Beverage',
    subcategory: 'Beverages & Confectionery',
    supplier: 'Sysco Corp.',
    ageInYard: 1,
    palletCount: 5,
    estimatedUnits: 720,
    truckId: 'TRK-445',
    dockAssigned: 'Dock 2',
    priority: 'low',
    initialEstimate: {
      certainty: 78,
      totalHours: 14.0,
      breakdown: { unloading: 2.5, binning: 9.0, crossdocking: 2.5 },
      byZone: {
        'Zone A': { hours: 3.0, units: 160 },
        'Zone B': { hours: 6.5, units: 380 },
        'Zone C': { hours: 2.0, units: 120 },
        'Zone D': { hours: 0.0, units: 0 },
        'Crossdock': { hours: 2.5, units: 60 },
      },
    },
    updatedEstimate: null,
    criteria: {
      workloadBalance:      { score: 0.62, label: 'Moderate' },
      ageScore:             { score: 0.15, label: 'Low' },
      processingEfficiency: { score: 0.82, label: 'High' },
      overall: 0.41,
    },
    updatedCriteria: null,
    isRecommended: false,
    isUpdatedRecommended: false,
    recommendationReasons: [],
  },
]

// ─── Scan Items for CONT-4201 ──────────────────────────────────────────────────
// Items 0-4: normal dry goods (no alerts)
// Items 5-7: cold-chain items (unexpected — not declared in PO)
// Item 7 triggers re-estimation
// Item 8: oversized item
// Item 9: normal again
export const SCAN_ITEMS = [
  {
    id: 'PKG-001',
    type: 'Packaged Goods',
    brand: 'Harvest Select',
    description: 'Assorted Canned Vegetables (case of 48)',
    color: 'Multicolor — assorted labels',
    weightKg: 11.2,
    dimensions: '45 × 30 × 25 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: false,
    destination: 'Zone B',
    handlingMinutes: 8,
    alert: null,
  },
  {
    id: 'PKG-002',
    type: 'Bottled Beverages',
    brand: 'NatureFresh',
    description: 'Assorted Fruit Juices — 24-pack',
    color: 'Clear bottles / Orange-Green labels',
    weightKg: 14.8,
    dimensions: '40 × 35 × 30 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: false,
    destination: 'Zone B',
    handlingMinutes: 10,
    alert: null,
  },
  {
    id: 'PKG-003',
    type: 'Dry Goods',
    brand: 'Granary Mills',
    description: 'Pasta & Grain Assortment — bulk case',
    color: 'Kraft paper / Beige',
    weightKg: 8.5,
    dimensions: '50 × 40 × 20 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: false,
    destination: 'Zone B',
    handlingMinutes: 7,
    alert: null,
  },
  {
    id: 'PKG-004',
    type: 'Breakfast Foods',
    brand: 'MorningStar',
    description: 'Cereals & Granola — mixed case (12 SKUs)',
    color: 'Bright mixed packaging',
    weightKg: 6.2,
    dimensions: '55 × 40 × 35 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: false,
    destination: 'Zone A',
    handlingMinutes: 9,
    alert: null,
  },
  {
    id: 'PKG-005',
    type: 'Cooking Supplies',
    brand: 'OlivePress',
    description: 'Extra Virgin Olive Oil — 6 × 1L bottles',
    color: 'Green / Gold glass bottles',
    weightKg: 7.8,
    dimensions: '35 × 35 × 40 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: true,
    destination: 'Zone B',
    handlingMinutes: 11,
    alert: null,
  },
  {
    id: 'PKG-006',
    type: 'Dairy Products',
    brand: 'ColdFresh Dairy Co.',
    description: 'Assorted Cheese & Butter — bulk pack',
    color: 'White / Blue vacuum-sealed film',
    weightKg: 12.4,
    dimensions: '40 × 40 × 30 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: true,
    coldChainTemp: '2°C – 4°C',
    fragile: false,
    destination: 'Zone D',
    handlingMinutes: 22,
    alert: {
      type: 'cold-chain',
      severity: 'warning',
      message: 'Cold chain required (2–4°C) — not declared in PO. Routing to Zone D (Cold Storage).',
    },
  },
  {
    id: 'PKG-007',
    type: 'Frozen Meals',
    brand: 'QuickFreeze',
    description: 'Pre-packaged Frozen Entrees — 48-pack',
    color: 'White / Red thermal packaging',
    weightKg: 18.6,
    dimensions: '60 × 50 × 35 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: true,
    coldChainTemp: '−18°C',
    fragile: false,
    destination: 'Zone D',
    handlingMinutes: 25,
    alert: {
      type: 'cold-chain',
      severity: 'warning',
      message: 'Frozen goods — requires deep-freeze handling (−18°C). PO declared ambient storage.',
    },
  },
  {
    id: 'PKG-008',
    type: 'Dairy — Yogurt',
    brand: 'LiveCulture',
    description: 'Probiotic Yogurt Multipack — 36 units',
    color: 'White / Green cup packaging',
    weightKg: 9.8,
    dimensions: '45 × 30 × 25 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: true,
    coldChainTemp: '1°C – 5°C',
    fragile: false,
    destination: 'Zone D',
    handlingMinutes: 20,
    triggersReestimation: true,   // This item triggers workload re-estimation
    alert: {
      type: 'cold-chain',
      severity: 'critical',
      message: '3rd cold-chain item detected. Zone D currently at 89% capacity. Triggering workload re-estimation.',
    },
  },
  {
    id: 'PKG-009',
    type: 'Beverages — Oversized',
    brand: 'AquaStream',
    description: 'Water Dispenser Tanks — 12 × 20 L',
    color: 'Clear / Blue caps',
    weightKg: 48.0,
    dimensions: '120 × 80 × 80 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: false,
    oversized: true,
    destination: 'Zone B',
    handlingMinutes: 18,
    alert: {
      type: 'oversized',
      severity: 'warning',
      message: 'Oversized — requires forklift and extended processing lane. Manual routing applied.',
    },
  },
  {
    id: 'PKG-010',
    type: 'Condiments',
    brand: 'SavorMax',
    description: 'Mixed Sauces & Condiments — glass jars',
    color: 'Multi-color glass jar labels',
    weightKg: 10.2,
    dimensions: '35 × 35 × 30 cm',
    condition: 'Good',
    hazardous: false,
    requiresColdChain: false,
    fragile: true,
    destination: 'Zone B',
    handlingMinutes: 12,
    alert: null,
  },
]

// ─── Helper functions ──────────────────────────────────────────────────────────
export function getScoreColor(score) {
  if (score >= 0.80) return 'text-green-600'
  if (score >= 0.60) return 'text-blue-600'
  if (score >= 0.40) return 'text-amber-600'
  return 'text-red-600'
}

export function getScoreBarClass(score) {
  if (score >= 0.80) return 'bg-green-500'
  if (score >= 0.60) return 'bg-blue-500'
  if (score >= 0.40) return 'bg-amber-500'
  return 'bg-red-500'
}

export function getPriorityConfig(priority) {
  const map = {
    urgent: { label: 'URGENT',  bg: 'bg-red-100',    text: 'text-red-700',    dot: 'bg-red-500' },
    high:   { label: 'HIGH',    bg: 'bg-amber-100',  text: 'text-amber-700',  dot: 'bg-amber-500' },
    normal: { label: 'NORMAL',  bg: 'bg-blue-100',   text: 'text-blue-700',   dot: 'bg-blue-500' },
    low:    { label: 'LOW',     bg: 'bg-slate-100',  text: 'text-slate-600',  dot: 'bg-slate-400' },
  }
  return map[priority] || map.normal
}

export function getCategoryAbbr(category) {
  const map = {
    'Food & Beverage':       'F&B',
    'Consumer Electronics':  'Electronics',
    'Home & Garden':         'Home & Garden',
    'Sports & Outdoor':      'Sports',
    'Apparel & Accessories': 'Apparel',
    'Health & Beauty':       'Beauty',
    'Automotive Parts':      'Automotive',
  }
  return map[category] || category
}

// ─── Labor: Workers ────────────────────────────────────────────────────────────
// 22 workers per zone (108 total).  Compact format mapped to full objects.
// Zone D: all 22 absent from this AM shift → 0 h capacity (critical alert).
// Columns: id · name · zone · role · checkedIn(1/0) · time · expA·B·C·D·XD
const _W = [
  // ── Zone A (22 workers, 17 checked in) ─────────────────────────────────────
  ['W001','Priya Nair',        'Zone A','Lead Receiver',       1,'05:45', 36,4, 2,8, 6],
  ['W002','Maria Santos',      'Zone A','Receiver',            1,'05:52', 18,2, 0,3, 0],
  ['W003','Diego Reyes',       'Zone A','Receiver',            1,'06:08', 12,0, 0,0, 2],
  ['W013','Elena Petrov',      'Zone A','Senior Receiver',     1,'06:01', 24,3, 0,5, 0],
  ['W014','Marcus Williams',   'Zone A','Senior Receiver',     1,'05:58', 30,6, 0,0, 0],
  ['W015','Yuki Tanaka',       'Zone A','Receiver',            1,'06:12', 16,0, 0,0, 0],
  ['W016','Andre Silva',       'Zone A','Receiver',            1,'06:04', 20,4, 0,0, 0],
  ['W017','Ling Wang',         'Zone A','Receiver',            1,'06:09', 14,0, 0,0, 0],
  ['W018','Omar Hassan',       'Zone A','Junior Receiver',     1,'06:18',  8,0, 0,0, 0],
  ['W019','Sophia Rossi',      'Zone A','Receiver',            1,'06:03', 18,0, 0,0, 0],
  ['W020','Luis Garcia',       'Zone A','Receiver',            1,'06:07', 22,0, 0,0, 0],
  ['W021','Keiko Sato',        'Zone A','Receiver',            1,'06:14', 15,2, 0,0, 0],
  ['W022','David Johnson',     'Zone A','Senior Receiver',     1,'06:06', 28,4, 0,0, 0],
  ['W023','Amira Khalil',      'Zone A','Junior Receiver',     1,'06:22',  6,0, 0,0, 0],
  ['W024','Jordan Brooks',     'Zone A','Receiver',            1,'06:11', 12,0, 0,0, 3],
  ['W025','Tasha Patel',       'Zone A','Receiver',            1,'06:16', 10,0, 0,0, 0],
  ['W026','Roberto Kim',       'Zone A','Receiver',            1,'06:19',  8,0, 0,0, 0],
  ['W027','Mei Osei',          'Zone A','Receiver',            0,  null,  14,0, 0,0, 0],
  ['W028','Jamal Andersen',    'Zone A','Receiver',            0,  null,  10,3, 0,0, 0],
  ['W029','Ingrid Yamamoto',   'Zone A','Senior Receiver',     0,  null,  32,0, 0,0, 0],
  ['W030','Kwame Ferreira',    'Zone A','Receiver',            0,  null,   9,0, 0,0, 0],
  ['W031','Nadia Novak',       'Zone A','Receiver',            0,  null,   7,0, 0,0, 0],
  // ── Zone B (22 workers, 17 checked in) ─────────────────────────────────────
  ['W004','James Park',        'Zone B','Lead Stower',         1,'06:02',  6,28,8, 0, 0],
  ['W005','Aisha Thompson',    'Zone B','Senior Stower',       1,'06:15',  0,18,4, 0, 3],
  ['W006','Fatima Al-Hassan',  'Zone B','Stower',              1,'06:20',  2,14,0, 0, 0],
  ['W007','Carlos Mendoza',    'Zone B','Stower',              0,  null,   0, 8,0, 0, 0],
  ['W032','Leila Vasquez',     'Zone B','Stower',              1,'06:05',  0,22,0, 0, 0],
  ['W033','Antoine Dubois',    'Zone B','Stower',              1,'06:11',  0,16,3, 0, 0],
  ['W034','Zara Bergmann',     'Zone B','Senior Stower',       1,'06:08',  0,26,0, 0, 0],
  ['W035','Finn Murphy',       'Zone B','Stower',              1,'06:03',  3,14,0, 0, 0],
  ['W036','Hana Nakamura',     'Zone B','Stower',              1,'06:17',  0,18,2, 0, 0],
  ['W037','Marco Adeyemi',     'Zone B','Junior Stower',       1,'06:14',  0, 6,0, 0, 0],
  ['W038','Yara Johnson',      'Zone B','Stower',              1,'06:21',  0,20,0, 0, 0],
  ['W039','Dion Mitchell',     'Zone B','Stower',              1,'06:09',  0,15,0, 0, 2],
  ['W040','Alex Turner',       'Zone B','Stower',              1,'06:13',  0,10,4, 0, 0],
  ['W041','Robin Casey',       'Zone B','Senior Stower',       1,'06:07',  0,24,0, 0, 0],
  ['W042','Dana Fuller',       'Zone B','Stower',              1,'06:00',  0,14,0, 0, 0],
  ['W043','Tyler Stone',       'Zone B','Junior Stower',       1,'06:18',  0, 7,0, 0, 0],
  ['W044','Casey Reed',        'Zone B','Stower',              1,'06:22',  0,18,0, 0, 0],
  ['W045','Morgan Lane',       'Zone B','Junior Stower',       1,'06:25',  0, 5,0, 0, 0],
  ['W046','Sam Cruz',          'Zone B','Stower',              0,  null,   0,12,0, 0, 0],
  ['W047','Jamie Ross',        'Zone B','Stower',              0,  null,   0, 9,0, 0, 0],
  ['W048','Avery Flynn',       'Zone B','Stower',              0,  null,   0,11,0, 0, 0],
  ['W049','Blake Hart',        'Zone B','Stower',              0,  null,   0, 8,0, 0, 0],
  // ── Zone C (22 workers, 14 checked in) ─────────────────────────────────────
  ['W008','Kevin Liu',         'Zone C','P&P Specialist',      1,'06:10',  4,6, 20,0, 8],
  ['W009',"Sara O'Brien",      'Zone C','Pick & Pack',         0,  null,   0,0, 10,0, 0],
  ['W050','Taylor Knight',     'Zone C','P&P Specialist',      1,'06:05',  0,0, 18,0, 0],
  ['W051','Lennon Warren',     'Zone C','Pick & Pack',         1,'06:12',  2,0, 14,0, 0],
  ['W052','Finley Wood',       'Zone C','Pick & Pack',         1,'06:08',  0,0, 12,0, 0],
  ['W053','Remy Spencer',      'Zone C','Pick & Pack',         1,'06:15',  0,0, 16,0, 0],
  ['W054','Bellamy Kim',       'Zone C','P&P Specialist',      1,'06:03',  0,0, 22,0, 0],
  ['W055','Shiloh Lewis',      'Zone C','Junior P&P',          1,'06:19',  0,0,  8,0, 0],
  ['W056','Luca Carter',       'Zone C','Pick & Pack',         1,'06:07',  0,3, 14,0, 0],
  ['W057','Nico Bailey',       'Zone C','Pick & Pack',         1,'06:11',  0,0, 10,0, 0],
  ['W058','Sasha Cooper',      'Zone C','Junior P&P',          1,'06:22',  0,0,  6,0, 0],
  ['W059','Kit Turner',        'Zone C','Pick & Pack',         1,'06:06',  0,0, 12,0, 0],
  ['W060','Micah Wright',      'Zone C','P&P Specialist',      1,'06:01',  0,0, 24,0, 0],
  ['W061','Raven Scott',       'Zone C','Pick & Pack',         1,'06:16',  0,0,  9,0, 0],
  ['W062','Phoenix Green',     'Zone C','Junior P&P',          0,  null,   0,0,  5,0, 0],
  ['W063','Storm Adams',       'Zone C','Pick & Pack',         0,  null,   0,0,  7,0, 0],
  ['W064','August Mitchell',   'Zone C','Pick & Pack',         0,  null,   0,0, 11,0, 0],
  ['W065','Cleo Davis',        'Zone C','P&P Specialist',      0,  null,   0,0, 16,0, 0],
  ['W066','Orion Rivera',      'Zone C','Pick & Pack',         0,  null,   0,0,  8,0, 0],
  ['W067','Atlas Edwards',     'Zone C','Pick & Pack',         0,  null,   0,0,  6,0, 0],
  ['W068','Zephyr Collins',    'Zone C','Pick & Pack',         0,  null,   0,0,  4,0, 0],
  ['W069','Lyric Morris',      'Zone C','Pick & Pack',         0,  null,   0,0,  3,0, 0],
  // ── Zone D (22 workers, 0 checked in – AM shift absent) ────────────────────
  ['W010','Tom Fischer',       'Zone D','Cold Storage Lead',   0,  null,   0,0,  0,32,0],
  ['W070','Ingrid Kolb',       'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,24,0],
  ['W071','Sven Nielsen',      'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,18,0],
  ['W072','Anya Sokolova',     'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,20,0],
  ['W073','Bjorn Larsen',      'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,16,0],
  ['W074','Natasha Morozova',  'Zone D','Cold Storage Tech',   0,  null,   0,0,  0,14,0],
  ['W075','Henrik Gustafsson', 'Zone D','Cold Storage Tech',   0,  null,   0,0,  0,22,0],
  ['W076','Olga Petrenko',     'Zone D','Cold Storage Tech',   0,  null,   0,0,  0,12,0],
  ['W077','Erik Eriksson',     'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,28,0],
  ['W078','Astrid Berg',       'Zone D','Cold Storage Tech',   0,  null,   0,0,  0,10,0],
  ['W079','Lars Hansen',       'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,18,0],
  ['W080','Freya Lindqvist',   'Zone D','Cold Storage Lead',   0,  null,   0,0,  0,26,0],
  ['W081','Harald Strand',     'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,15,0],
  ['W082','Sigrid Olsen',      'Zone D','Cold Storage Tech',   0,  null,   0,0,  0,11,0],
  ['W083','Morten Dahl',       'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,20,0],
  ['W084','Bente Christensen', 'Zone D','Cold Storage Op.',    0,  null,   0,0,  0, 8,0],
  ['W085','Gunnar Pedersen',   'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,16,0],
  ['W086','Ragnhild Andersen', 'Zone D','Cold Storage Tech',   0,  null,   0,0,  0,13,0],
  ['W087','Leif Eriksen',      'Zone D','Cold Storage Op.',    0,  null,   0,0,  0, 9,0],
  ['W088','Kari Haugen',       'Zone D','Cold Storage Tech',   0,  null,   0,0,  0, 7,0],
  ['W089','Tor Johansen',      'Zone D','Cold Storage Op.',    0,  null,   0,0,  0,11,0],
  ['W090','Marta Gustavsson',  'Zone D','Cold Storage Tech',   0,  null,   0,0,  0, 6,0],
  // ── Crossdock (20 workers, 13 checked in) ──────────────────────────────────
  ['W011','Nina Vasquez',      'Crossdock','Crossdock Lead',     1,'06:00', 3,2,3, 0,22],
  ['W012','Ben Okafor',        'Crossdock','Crossdock Operator', 1,'06:05', 2,4,6, 0,16],
  ['W091','Parker Webb',       'Crossdock','Crossdock Operator', 1,'06:08', 0,2,1, 0,10],
  ['W092','Cameron Grant',     'Crossdock','Crossdock Operator', 1,'06:11', 0,0,0, 0, 8],
  ['W093','Reese Burns',       'Crossdock','Senior Operator',    1,'06:03', 0,0,2, 0,14],
  ['W094','Spencer Fox',       'Crossdock','Crossdock Operator', 1,'06:15', 0,3,0, 0,12],
  ['W095','Emerson Cole',      'Crossdock','Crossdock Operator', 1,'06:07', 2,0,0, 0, 9],
  ['W096','Rowan Shaw',        'Crossdock','Junior Operator',    1,'06:19', 0,0,0, 0, 6],
  ['W097','Sage Barker',       'Crossdock','Crossdock Operator', 1,'06:04', 0,0,0, 0,11],
  ['W098','Skyler Pierce',     'Crossdock','Crossdock Operator', 1,'06:12', 0,0,0, 0, 8],
  ['W099','River Hayes',       'Crossdock','Crossdock Lead',     1,'06:02', 3,2,0, 0,20],
  ['W100','Blake Ford',        'Crossdock','Crossdock Operator', 1,'06:09', 0,0,0, 0, 7],
  ['W101','Quinn James',       'Crossdock','Junior Operator',    1,'06:22', 0,0,0, 0, 5],
  ['W102','Drew Summers',      'Crossdock','Crossdock Operator', 0,  null,  0,0,0, 0, 9],
  ['W103','Alex Park',         'Crossdock','Crossdock Operator', 0,  null,  0,0,0, 0, 7],
  ['W104','Jordan West',       'Crossdock','Crossdock Operator', 0,  null,  0,0,0, 0, 6],
  ['W105','Sam Rivera',        'Crossdock','Crossdock Operator', 0,  null,  0,4,0, 0, 8],
  ['W106','Casey Morgan',      'Crossdock','Crossdock Operator', 0,  null,  0,0,0, 0, 5],
  ['W107','Taylor Reed',       'Crossdock','Crossdock Operator', 0,  null,  0,0,1, 0, 7],
  ['W108','Morgan Cruz',       'Crossdock','Junior Operator',    0,  null,  0,0,0, 0, 4],
]

export const WORKERS = _W.map(([id, name, zone, role, inFlag, time, a, b, c, d, x]) => ({
  id,
  name,
  initials: name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase(),
  role,
  assignedZone: zone,
  checkedIn: !!inFlag,
  checkInTime: time,
  experience: { 'Zone A': a, 'Zone B': b, 'Zone C': c, 'Zone D': d, 'Crossdock': x },
}))

// ─── Labor: Workload & Capacity data by time period ───────────────────────────
// capacity = checked-in workers × remaining shift hours for that zone/period
// For "Current Shift": 7.8 h remaining per checked-in worker (06:10 into 06:00–14:00)
export const LABOR_PERIOD_DATA = {
  shift: {
    label: 'Current Shift',
    sublabel: '06:00 – 14:00',
    hoursLabel: 'hours',
    // Zone D capacity = 0 because Tom Fischer has not checked in
    zones: {
      'Zone A':    { estimated: 18,  done: 3,  capacity: 23.4 },
      'Zone B':    { estimated: 28,  done: 6,  capacity: 23.4 },
      'Zone C':    { estimated: 12,  done: 2,  capacity: 7.8  },
      'Zone D':    { estimated: 14,  done: 0,  capacity: 0    },
      'Crossdock': { estimated: 10,  done: 4,  capacity: 15.6 },
    },
  },
  today: {
    label: 'Today',
    sublabel: 'All 3 shifts',
    hoursLabel: 'hours',
    zones: {
      'Zone A':    { estimated: 52,  done: 8,  capacity: 58   },
      'Zone B':    { estimated: 78,  done: 14, capacity: 62   },
      'Zone C':    { estimated: 34,  done: 5,  capacity: 32   },
      'Zone D':    { estimated: 40,  done: 0,  capacity: 22   },
      'Crossdock': { estimated: 28,  done: 9,  capacity: 45   },
    },
  },
  twodays: {
    label: 'Next 2 Days',
    sublabel: 'Incl. today',
    hoursLabel: 'hours',
    zones: {
      'Zone A':    { estimated: 110, done: 8,  capacity: 120  },
      'Zone B':    { estimated: 160, done: 14, capacity: 125  },
      'Zone C':    { estimated: 72,  done: 5,  capacity: 65   },
      'Zone D':    { estimated: 85,  done: 0,  capacity: 44   },
      'Crossdock': { estimated: 60,  done: 9,  capacity: 90   },
    },
  },
  week: {
    label: 'This Week',
    sublabel: 'Mon – Fri',
    hoursLabel: 'hours',
    zones: {
      'Zone A':    { estimated: 380, done: 8,  capacity: 420  },
      'Zone B':    { estimated: 540, done: 14, capacity: 440  },
      'Zone C':    { estimated: 240, done: 5,  capacity: 230  },
      'Zone D':    { estimated: 290, done: 0,  capacity: 155  },
      'Crossdock': { estimated: 210, done: 9,  capacity: 315  },
    },
  },
}

// ─── Labor: Rebalancing recommendations ───────────────────────────────────────
export const REBALANCING_RECS = [
  {
    id: 'REC-001',
    priority: 'critical',
    workerId: 'W001',   // Priya Nair
    fromZone: 'Zone A',
    toZone: 'Zone D',
    experienceMonths: 8,
    surplusPeriodKey: 'Zone A',
    deficitPeriodKey: 'Zone D',
    reasoning: "Zone D has zero available capacity (Tom Fischer absent) against 14 h of workload. Priya Nair has the highest Zone D experience (8 mo.) among Zone A workers, and Zone A currently has an 8.4 h labor surplus.",
    impact: 'Resolves ~7.8 h of Zone D deficit for current shift',
  },
  {
    id: 'REC-002',
    priority: 'high',
    workerId: 'W012',   // Ben Okafor
    fromZone: 'Crossdock',
    toZone: 'Zone C',
    experienceMonths: 4,
    surplusPeriodKey: 'Crossdock',
    deficitPeriodKey: 'Zone C',
    reasoning: "Zone C is 2.2 h short with Sara O'Brien absent. Ben Okafor has 4 months Zone C experience and Crossdock has a 9.6 h surplus that can absorb the reallocation.",
    impact: 'Closes the Zone C 2.2 h gap for current shift',
  },
]

// ─── Labor helpers ─────────────────────────────────────────────────────────────
export function getExperienceLevel(months) {
  if (months >= 36) return { dots: 5, label: 'Expert',      color: 'text-emerald-600' }
  if (months >= 24) return { dots: 4, label: 'Senior',      color: 'text-blue-600'    }
  if (months >= 12) return { dots: 3, label: 'Proficient',  color: 'text-blue-500'    }
  if (months >= 6)  return { dots: 2, label: 'Developing',  color: 'text-amber-600'   }
  if (months >= 1)  return { dots: 1, label: 'Beginner',    color: 'text-slate-500'   }
  return              { dots: 0, label: 'No exp.',     color: 'text-slate-400'   }
}
